sudo: required
language: node_js
node_js:
   - "7.9"

services:
  - docker

before_install:
  - docker pull justinribeiro/chrome-headless
  - docker run -d --net host justinribeiro/chrome-headless
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker ps -a
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git config --list
  - git remote set-url origin git@github.com:A-gambit/CSS-IN-JS-Benchmarks.git

install:
  - cd ./packages/big-table-test/ && yarn

cache:
  yarn: true

script:
  - npm run start

after_success:
  - cd ../../
  - git add RESULT.md
  - git commit -m 'Travis CI Automaticaly Benchmarks'
  - git push origin HEAD:$BRANCH
