sudo: required
language: node_js
node_js:
   - "7.9"

services:
  - docker

before_install:
  - docker pull justinribeiro/chrome-headless
  - docker run -d --net host justinribeiro/chrome-headless
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker ps -a

install:
  - cd ./packages/big-table-test/ && yarn

cache:
  yarn: true

script:
  - npm run start
  - git add RESULT.md
  - git commit -m 'Travis CI Automaticaly Benchmarks'
  - git push
