sudo: required
language: node_js
node_js:
   - "7.9"

services:
  - docker

before_install:
  - docker pull justinribeiro/chrome-headless
  - docker run -d --net host justinribeiro/chrome-headless
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker ps -a
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git config --list

install:
  - npm install lerna
  - lerna bootstrap
  - npm install

cache:
  yarn: true

env:
  - NODE_ENV: production

script:
  - NODE_ENV=production && npm run benchmark

after_success:
  - git config user.name "A-gambit"
  - git config user.email "a.gambit.gregory@gmail.com"
  - git config user.password $GIT_TOKEN
  - git remote add upstream "https://$GIT_TOKEN@github.com/A-gambit/CSS-IN-JS-Benchmarks.git"
  - git fetch upstream
  - git reset upstream/$BRANCH
  - git add RESULT.md
  - git commit -m 'Travis CI Automaticaly Benchmarks Update [ci skip]'
  - git push -q upstream HEAD:$BRANCH
